### PR TITLE
work related to command_center

### PR DESCRIPTION
**Pull request by jurij-jukic**

### CODE REVIEW

**Comment by Tenari** [comment]
fyi, `kit b` on this branch failed on my machine, and also the Readme references a non-existent file `tg/src/tg_api.rs`

**Comment by jurij-jukic** [comment]
> fyi, `kit b` on this branch failed on my machine, and also the Readme references a non-existent file `tg/src/tg_api.rs`

can you share the output of `kit b`? it works on my machine

the [referenced file](https://github.com/kinode-dao/command_center/blob/jurij/command_center/src/tg_api.rs) can be found in command center, the app which uses this repo. i will add the link to the readme

**Comment by bitful-pannul** [comment]
> > fyi, `kit b` on this branch failed on my machine, and also the Readme references a non-existent file `tg/src/tg_api.rs`
> 
> can you share the output of `kit b`? it works on my machine
> 
> the [referenced file](https://github.com/kinode-dao/command_center/blob/jurij/command_center/src/tg_api.rs) can be found in command center, the app which uses this repo. i will add the link to the readme

I think this error:

```
   error: failed to read path for WIT [/Users/korin/mars/tenari/telegram-bot/tg/wit]

             Caused by:
               No such file or directory (os error 2)
        --> tg/src/lib.rs:21:1
         |
      21 | / wit_bindgen::generate!({
      22 | |     path: "wit",
      23 | |     world: "process",
      24 | | });
         | |__^
         |
         = note: this error originates in the macro `wit_bindgen::generate` (in Nightly builds, run with -Z macro-backtrace for more info)

      error: cannot find macro `export` in this scope
         --> tg/src/lib.rs:207:1
          |
      207 | call_init!(init);
          | ^^^^^^^^^^^^^^^^
          |
          = note: this error originates in the macro `call_init` (in Nightly builds, run with -Z macro-backtrace for more info)

      error[E0405]: cannot find trait `Guest` in this scope
         --> tg/src/lib.rs:207:1
          |
      207 | call_init!(init);
          | ^^^^^^^^^^^^^^^^ not found in this scope
          |
          = note: this error originates in the macro `call_init` (in Nightly builds, run with -Z macro-backtrace for more info)

      For more information about this error, try `rustc --explain E0405`.
      error: could not compile `tg` (lib) due to 3 previous errors
   0:

Location:
   src/build/mod.rs:56
```

**Comment by bitful-pannul** [comment]
ok @jurij-jukic @Tenari wit weirdness + spawn leading to 0.7.0 error fixed in [c8e9829](https://github.com/kinode-dao/telegram-bot/pull/3/commits/c8e9829bb4bd5f2f4e69b9c2730f41fbaf09c322).

twas outdated process_lib (which pulled in new wit types), changing the wit_bindgen to target/wit and "process" to "process-v0". 

Test it out, we should merge this PR (sorry for long hanging) and clean up branches

**Review by barraguda — APPROVED** [review]
we should merge this to main now that 0.8.0 works, 
@jurij-jukic @jaxs-ribs plz take a look and test, but lgtm

note for testing, checking if command_center//other apps do not break when zen/reset disappears

**Comment by jurij-jukic** [comment]
> we should merge this to main now that 0.8.0 works, @jurij-jukic @jaxs-ribs plz take a look and test, but lgtm
> 
> note for testing, checking if command_center//other apps do not break when zen/reset disappears

zen/reset is not being imported by any app explicity through cargo.toml afaik, so it should be fine

**Pull request merged**
